-- Documentos del evento (por cotización), categorizados.
-- Categorías: 'contratos' | 'ordenes_compra' | 'facturas' | 'otros'.
CREATE TABLE IF NOT EXISTS public.event_documents (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  quotation_id uuid NOT NULL REFERENCES public.quotations(id) ON DELETE CASCADE,
  category text NOT NULL,
  file_name text NOT NULL,
  file_url text NOT NULL,
  uploaded_at timestamptz NOT NULL DEFAULT now()
);

GRANT ALL ON public.event_documents TO anon, authenticated;
